# Generated by Django 3.2.15 on 2023-02-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20221215_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-id']},
        ),
    ]
