# Generated by Django 3.2.15 on 2023-02-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20230221_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantcuisine',
            options={'verbose_name_plural': 'Restaurant Cuisines'},
        ),
    ]
