# Generated by Django 3.2.15 on 2023-02-18 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0002_alter_favourite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourite',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
